webtalk_init -webtalk_dir /home/ctnguyen/work/VGA_controller/VGA_controller.sim/sim_1/behav/xsim.dir/tb_VGA_controller_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Mar 11 22:34:15 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1368829" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174620556_1777490017_210608343_300" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4090d47f-f218-4feb-92f0-48ddc1c66e29" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b0b60187fa28413c8ee62a756276f47d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Scientific" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Scientific Linux release 6.7 (Carbon)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2000.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "8775480 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "351772_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3218114784 -regid "174620556_1777490017_210608343_300" -xml /home/ctnguyen/work/VGA_controller/VGA_controller.sim/sim_1/behav/xsim.dir/tb_VGA_controller_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ctnguyen/work/VGA_controller/VGA_controller.sim/sim_1/behav/xsim.dir/tb_VGA_controller_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ctnguyen/work/VGA_controller/VGA_controller.sim/sim_1/behav/xsim.dir/tb_VGA_controller_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
